/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#b1fbff',
        'primary-fixed-dim': '#c9d4f0',
        'secondary-dim': '#415660',
        'on-primary': '#f7f7ff',
        'on-tertiary-fixed-variant': '#1b6d71',
        'inverse-surface': '#0c0f10',
        'surface-container-low': '#f1f4f6',
        'secondary-fixed-dim': '#c1d8e4',
        'surface-variant': '#dbe4e7',
        'on-secondary-fixed-variant': '#495f69',
        'on-tertiary-container': '#066266',
        'on-surface': '#2b3437',
        'surface-container-highest': '#dbe4e7',
        'on-secondary': '#f2faff',
        'surface': '#f8f9fa',
        'surface-container': '#eaeff1',
        'secondary': '#4d626c',
        'primary-dim': '#48526a',
        'surface-bright': '#f8f9fa',
        'error-dim': '#4e0309',
        'background': '#f8f9fa',
        'outline': '#737c7f',
        'on-primary-container': '#475269',
        'error': '#9f403d',
        'surface-container-high': '#e3e9ec',
        'error-container': '#fe8983',
        'on-error-container': '#752121',
        'tertiary-dim': '#005d61',
        'primary-fixed': '#d7e2ff',
        'on-primary-fixed-variant': '#515c73',
        'primary-container': '#d7e2ff',
        'surface-dim': '#d1dce0',
        'tertiary-fixed-dim': '#a3ecf0',
        'secondary-container': '#cfe6f2',
        'on-secondary-fixed': '#2d424c',
        'on-background': '#2b3437',
        'inverse-primary': '#d7e2ff',
        'surface-container-lowest': '#ffffff',
        'on-tertiary': '#e4feff',
        'primary': '#545e76',
        'on-surface-variant': '#586064',
        'tertiary': '#15696d',
        'surface-tint': '#545e76',
        'outline-variant': '#abb3b7',
        'on-error': '#fff7f6',
        'on-primary-fixed': '#353f56',
        'tertiary-fixed': '#b1fbff',
        'secondary-fixed': '#cfe6f2',
        'inverse-on-surface': '#9b9d9e',
        'on-tertiary-fixed': '#004f52',
        'on-secondary-container': '#40555f',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl': '0.75rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
