#!/usr/bin/env python3
"""
Layer 1 – Requirements Layer CLI runner.

Usage:
  uv run src/requirement_layer/runner.py --input src/requirement_layer/mock_data/mock_ascorbic_acid.json
  uv run src/requirement_layer/runner.py --input src/requirement_layer/mock_data/mock_citric_acid.json --output out.json
  uv run src/requirement_layer/runner.py --input src/requirement_layer/mock_data/mock_natural_vanilla_flavor.json --model gemini-2.5-flash-preview

Environment variables:
  GEMINI_API_KEY   (required – Google AI Studio key)
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path

from dotenv import load_dotenv

# Allow running from the layer1/ directory
sys.path.insert(0, str(Path(__file__).parent))

from src.requirement_layer.input_processor import InputProcessor
from src.requirement_layer.output_formatter import OutputFormatter
from src.requirement_layer.requirement_engine import RequirementEngine
from src.requirement_layer.schemas.models import ErrorResponse

load_dotenv()
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)
logger = logging.getLogger("layer1.runner")


def run(
    input_data: dict,
    output_path: str | None = None,
    model: str = "gemini-2.5-flash-preview",
) -> dict:
    """
    Execute the Layer 1 pipeline end-to-end.

    Returns the output payload as a dict (also writes to output_path if provided).
    """
    processor = InputProcessor()
    formatter = OutputFormatter()

    # -- Input --
    try:
        payload = processor.load_from_dict(input_data)
    except ValueError as exc:
        error = ErrorResponse(error="Invalid input", detail=str(exc))
        result = error.model_dump()
        print(json.dumps(result, indent=2))
        sys.exit(1)

    logger.info(
        "Processing ingredient: %s (%s)",
        payload.ingredient.canonical_name,
        payload.ingredient.ingredient_id,
    )

    # -- Requirement generation --
    try:
        engine = RequirementEngine(model=model)
    except OSError as exc:
        error = ErrorResponse(error="Configuration error", detail=str(exc))
        result = error.model_dump()
        print(json.dumps(result, indent=2))
        sys.exit(1)

    requirements = engine.generate(
        ingredient=payload.ingredient,
        context=payload.context,
        ingredient_id=payload.ingredient.ingredient_id,
    )

    logger.info("Generated %d requirements", len(requirements))

    # -- Output --
    output = formatter.build(
        ingredient_id=payload.ingredient.ingredient_id,
        requirements=requirements,
        notes=f"Generated by Layer 1 RequirementEngine for {payload.ingredient.canonical_name}",
    )

    result = formatter.to_dict(output)

    if output_path:
        formatter.write_file(output, output_path)
        logger.info("Output written to %s", output_path)

    print(json.dumps(result, indent=2))
    return result


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Layer 1 Requirements Layer – generate ingredient quality requirements",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--input",
        "-i",
        required=True,
        help="Path to input JSON file (Layer 1 input contract)",
    )
    parser.add_argument(
        "--output",
        "-o",
        default=None,
        help="Optional path to write output JSON file",
    )
    parser.add_argument(
        "--model",
        default="gemini-2.5-flash-preview",
        help="Gemini model to use (default: gemini-2.5-flash-preview)",
    )
    args = parser.parse_args()
    
    with open(args.input, "r", encoding="utf-8") as f:
        input_data = json.load(f)

    run(input_data, args.output, args.model)


if __name__ == "__main__":
    main()
